url: http://uncommonplaces.com
name: Ida C. Benedetto
description: >
  Experience Design & Media Strategy

permalink:    /:year/:month/:title/

collections:
  projects:
    output: true
    permalink: /projects/:path/

